#!/bin/bash
# Note that although the script runs when parallelized, the coverage results are wrong.

echo 'Running tests...'
pytest -v test_immunity.py --cov-config=.coveragerc --cov=../covasim --durations=0

echo 'Creating HTML report...'
coverage html

echo 'Printing report...'
coverage report

echo 'Report location:'
echo "`pwd`/htmlcov/index.html"