#!/bin/bash
# Run both integration and unit tests
# Requires pytest-parallel:
#   pip install pytest-parallel

# Change to root folder
cd ..


echo "RUNNING ALL TESTS"

echo "STEP 1: RUNNING INTEGRATION TESTS"
pytest --workers auto tests/test*.py

echo "STEP 2: RUNNING UNIT TESTS"
pytest --workers auto tests/unittests/test*.py

echo "STEP 3: RUNNING EXAMPLES"
pytest --workers auto ./examples/*.py