'''
Load an old simulation to test regression.

Saved file originally generated by checking out Covasim v1.7.0 (with this file
not checked in) and running:

    import test_regression as tr
    tr.make_msim(do_save=True)
'''

import sciris as sc
import covasim as cv

pop_size = 500
beta1 = 0.01
beta2 = 0.02
filename = 'example_regression.msim'
version = '1.7.0'


def make_msim(do_save=False):

    # Shared settings
    kwargs = dict(pop_size=pop_size, verbose=0)

    # Versioning was introduced in 2.0
    if cv.check_version('2.0.0', verbose=False) >= 0:
        kwargs.update({'version':version})

    sim1 = cv.Sim(label='Sim 1', beta=beta1, **kwargs)
    sim2 = cv.Sim(label='Sim 2', beta=beta2, **kwargs)
    msim = cv.MultiSim(sims=[sim1, sim2])
    msim.run()
    msim.reduce()

    if do_save:
        print(msim.base_sim.summary)
        msim.save(filename)

    return msim


def test_migration_regression():
    sc.heading('Testing migration and regression...')

    msim1 = cv.MultiSim.load(filename)
    msim2 = make_msim()

    # Check that they match
    cv.diff_sims(msim1.base_sim, msim2.base_sim, die=True)

    return msim1,msim2



#%% Run as a script
if __name__ == '__main__':

    # Start timing and optionally enable interactive plotting
    T = sc.tic()

    msim1,msim2 = test_migration_regression()

    sc.toc(T)
    print('Done.')