#!/usr/bin/env python3

'''
Run this script to regenerate the baseline.
'''

import covasim as cv

filename = 'baseline.json'
keys = 'summary'

print('Updating baseline values...')

sim = cv.Sim(verbose=0)
sim.run()
sim.to_json(filename=filename, keys=keys)

print('Done.')
