apiVersion: v1
kind: Service
metadata:
  labels:
    service: covasim
  name: covasim
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    service: covasim
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: covasim
  name: covasim
spec:
  replicas: 2
  selector:
    matchLabels:
      service: covasim
  strategy: {}
  template:
    metadata:
      labels:
        service: covasim
    spec:
      containers:
      - image: "registry.hub.docker.com/jules2689/covasim:latest"
        name: covasim
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}

