name: Covasim CI workflow
on: [pull_request]

jobs:
  install_and_test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        python-version: ['3.11']
    name: Run tests
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Covasim
        run: pip install -e .
      - name: Install tests
        working-directory: ./tests
        run: pip install -r requirements_test.txt
      - name: Run integration tests
        working-directory: ./tests
        run: pytest -v test_*.py unittests/test_*.py -n auto --durations=0 --junitxml=test-results.xml
      - name: Publish test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: tests/test-results.xml
